# Current desktop theme
general.import = [ "~/.config/alacritty/themes/gruvbox.toml" ]

# Settings
general.live_config_reload = true

# Font
[font]
size = 10.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "SemiBold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

# Window
[window]
padding = { x = 20, y = 20 }
