# +==========================================================================+
#
#
#    █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
#   ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#   ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
#   ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
#   ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
#   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
#
#
# +==========================================================================+

# Current desktop theme
import = [ "~/.config/alacritty/themes/gruvbox.toml" ]

# Settings
live_config_reload = true

[font]
size = 11.5

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "SemiBold Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "SemiBold"

[window.padding]
x = 20
y = 10
