[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[colors.normal]
black = "#414868"
red = "#f7768e"
green = "#73daca"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[colors.bright]
black = "#555e87"
red = "#f88b9f"
green = "#88e0d2"
yellow = "#e5bb7f"
blue = "#8eb0f8"
magenta = "#c5a9f8"
cyan = "#90d6ff"
white = "#c9d2f6"
