# +==================================================================================+
#
#
#     ██████╗ ██╗  ██╗    ███╗   ███╗██╗   ██╗    ██████╗  ██████╗ ███████╗██╗  ██╗
#    ██╔═══██╗██║  ██║    ████╗ ████║╚██╗ ██╔╝    ██╔══██╗██╔═══██╗██╔════╝██║  ██║
#    ██║   ██║███████║    ██╔████╔██║ ╚████╔╝     ██████╔╝██║   ██║███████╗███████║
#    ██║   ██║██╔══██║    ██║╚██╔╝██║  ╚██╔╝      ██╔═══╝ ██║   ██║╚════██║██╔══██║
#    ╚██████╔╝██║  ██║    ██║ ╚═╝ ██║   ██║       ██║     ╚██████╔╝███████║██║  ██║
#     ╚═════╝ ╚═╝  ╚═╝    ╚═╝     ╚═╝   ╚═╝       ╚═╝      ╚═════╝ ╚══════╝╚═╝  ╚═╝
#
#
# +==================================================================================+

version = 2

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  foreground = "#45F1C2"
  style = "plain"
  template = " {{ .UserName }} on"
  type = "session"

  [[blocks.segments]]
  foreground = "#0CA0D8"
  style = "plain"
  template = "  {{ .Path }} "
  type = "path"

    [blocks.segments.properties]
    folder_separator_icon = "/"
    style = "full"

  [[blocks.segments]]
  foreground = "#14A5AE"
  powerline_symbol = ""
  style = "plain"
  template = "{{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
  type = "git"

    [blocks.segments.properties]
    fetch_stash_count = true
    fetch_upstream_icon = true

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#cd5e42"
  style = "plain"
  template = " "
  type = "root"

  [[blocks.segments]]
  foreground = "#CD4277"
  style = "plain"
  template = "# "
  type = "text"
