# Module decorators

[module/LEFT]
type = custom/text
label = "%{T2}%{T-}"
label-padding-left = 1
label-foreground = ${colors.raised}

[module/RIGHT]
type = custom/text
label = "%{T2}%{T-}"
label-padding-right = 1
label-foreground = ${colors.raised}

# Polybar modules

[module/logo]
type = custom/text
label = 
label-padding = 2
label-foreground = #1793d1
click-left = rofi -config ~/.config/rofi/rofi.rasi -show drun
click-right = rofi -config ~/.config/rofi/rofi.rasi -show window

[module/terminal]
type = custom/script
interval = 0.5
exec = [ "$(xdotool search --onlyvisible --class Alacritty)" ] && echo "%{F#ff7043}%{F-}  Terminal" || echo "  Terminal"
format-background = ${colors.raised}
format-overline = ${colors.background}
format-underline = ${colors.background}
format-padding = 2
click-left = i3-msg '[con_mark="terminal"] scratchpad show'

[module/explorer]
type = custom/script
interval = 0.5
exec = [ "$(xdotool search --onlyvisible --class Nemo)" ] && echo "%{F#ff7043}%{F-}  Explorer" || echo "  Explorer"
format-background = ${colors.raised}
format-overline = ${colors.background}
format-underline = ${colors.background}
format-padding = 2
click-left = i3-msg '[con_mark="explorer"] scratchpad show'

[module/workspaces]
type = internal/i3
pin-workspaces = true
reverse-scroll = false
wrapping-scroll = false
ws-icon-0 = 1;
ws-icon-1 = 2;󰝚
ws-icon-2 = 3;
ws-icon-3 = 4;󱚌
ws-icon-default = 
label-mode-padding = 2
label-mode-foreground = ${colors.urgent}
label-focused = %icon%
label-focused-padding = 3
label-focused-foreground = ${colors.foreground}
label-unfocused = %icon%
label-unfocused-padding = 3
label-unfocused-foreground = ${colors.empty}
label-visible = %icon%
label-visible-padding = 3
label-visible-foreground = ${colors.foreground-alt}
label-urgent = %icon%
label-urgent-padding = 3
label-urgent-foreground = ${colors.urgent}
label-mode = 󰲏

[module/output]
type = custom/script
label-padding = 2
interval = 0.5
exec = ~/.config/polybar/scripts/audio_icon.sh
click-left = ~/.config/polybar/scripts/audio_switcher.sh

[module/volume]
type = internal/pulseaudio
use-ui-max = false
format-volume = <bar-volume>
format-volume-padding = 2
format-muted = <bar-volume>
format-muted-padding = 2
bar-volume-width = 75
bar-volume-fill = 󱪼
bar-volume-empty = 󱪼
bar-volume-indicator = ""
bar-volume-gradient = false
bar-volume-foreground-0 = ${colors.foreground}
bar-volume-foreground-1 = ${colors.foreground}
bar-volume-foreground-2 = ${colors.foreground}
bar-volume-foreground-3 = ${colors.urgent}
bar-volume-empty-foreground = ${colors.empty}

[module/media]
type = custom/script
label-padding = 2
interval = 0.5
exec = [ "$(playerctl --player=spotify status 2> /dev/null)" = "Playing" ] && echo 󰏥 || echo 󰐌
click-left = playerctl --player=spotify play-pause
click-right = playerctl --player=spotify next
double-click-right = playerctl --player=spotify previous

[module/keyboard]
type = internal/xkeyboard
format = <label-layout>
format-padding = 2
label-layout = %icon%
layout-icon-0 = us;󰌌
layout-icon-1 = latam;%{F#ff7043}󰌓%{F}

[module/clipboard]
type = custom/text
label = 󰅇
label-padding = 2
click-left = CM_LAUNCHER=rofi clipmenu -config ~/.config/rofi/clipboard.rasi

[module/theme]
type = custom/text
label = 󰃝
label-padding = 2
click-left = ~/.config/i3/scripts/theme.sh toggle

[module/notifications]
type = custom/script
label-padding = 2
interval = 0.5
exec = [ "$(dunstctl is-paused)" = "true" ] && echo "%{F#ff7043}󱏫%{F-}" || echo 󰂚
click-left = dunstctl set-paused toggle

[module/network]
type = internal/network
interval = 5
interface-type = wired
format-connected = <label-connected>
label-connected = 
label-connected-padding = 2
format-disconnected = <label-disconnected>
label-disconnected = 
label-disconnected-padding = 2
label-disconnected-foreground = ${colors.urgent}

[module/temp]
type = custom/script
label-padding-left = 2
interval = 600
exec = echo "$(~/.config/polybar/scripts/weather.sh) at "
click-left = ~/.config/polybar/scripts/calendar.sh
scroll-up = ~/.config/polybar/scripts/calendar.sh next
scroll-down = ~/.config/polybar/scripts/calendar.sh prev

[module/date]
type = custom/script
label-padding-right = 2
interval = 1
exec = echo $(date +"%a %d %b, %I:%M %p")
click-left = ~/.config/polybar/scripts/calendar.sh
scroll-up = ~/.config/polybar/scripts/calendar.sh next
scroll-down = ~/.config/polybar/scripts/calendar.sh prev

[module/power]
type = custom/text
label = ⏼
label-padding = 2
label-foreground = ${colors.urgent}
click-left = ~/.config/polybar/scripts/power.sh
